# PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/telecomapp
spring.datasource.username=postgres
spring.datasource.password=Clave2026
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
