# PostgreSQL Railway
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
springdoc.api-docs.enabled=true
app.server-url=https://telecomapp-production.up.railway.app
spring.jpa.open-in-view=false
