# PostgreSQL Railway
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres.railway.internal:5432/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
springdoc.api-docs.enabled=false
spring.jpa.open-in-view=false
